import { useState } from "react";
import { SlidersHorizontal, X } from "lucide-react";
import MilestrideShell from "@/components/MilestrideShell";
import FleetMap from "@/components/FleetMap";
import { hubs, type Hub } from "@/lib/milestride";

export default function Overview() {
  const [overviewOpen, setOverviewOpen] = useState(true);
  const [selectedHub, setSelectedHub] = useState<Hub | null>(null);
  return <MilestrideShell><div className="relative min-h-[calc(100vh-4rem)] p-3 sm:p-5"><FleetMap onHubClick={setSelectedHub} />
    {!overviewOpen && <button onClick={() => setOverviewOpen(true)} className="absolute bottom-8 left-8 z-20 rounded-lg border border-[var(--ms-border)] bg-[var(--ms-panel)] px-4 py-3 text-xs font-semibold shadow-xl">Open Network Overview</button>}
    {overviewOpen && <NetworkCard onClose={() => setOverviewOpen(false)} />}
    {selectedHub && <HubDrawer hub={selectedHub} onClose={() => setSelectedHub(null)} />}
  </div></MilestrideShell>;
}

function NetworkCard({ onClose }: { onClose: () => void }) { return <div className="absolute bottom-8 left-8 z-20 w-[285px] rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)]/95 p-4 shadow-2xl backdrop-blur-md"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold">Network overview</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">Across 4 active hubs</p></div><button onClick={onClose} className="flex items-center gap-1 rounded px-2 py-1.5 text-[10px] font-medium text-[var(--ms-muted)] hover:bg-[var(--ms-hover)] hover:text-[var(--ms-body)]" title="Close overview"><X className="h-3.5 w-3.5" /> Close</button></div><div className="mb-4 grid grid-cols-3 divide-x divide-[var(--ms-border)]"><Metric value="4" label="Total hubs" /><Metric value="30" label="Available" color="text-[var(--ms-accent-strong)]" /><Metric value="3" label="Out of service" color="text-[#ef655a]" /></div><div className="space-y-1.5"><Notice color="amber" text="2 vehicles need charging" /><Notice color="red" text="1 geofence violation" /><Notice color="blue" text="6 scheduled for charging" /></div></div> }
function HubDrawer({ hub, onClose }: { hub: Hub; onClose: () => void }) { return <aside className="absolute right-8 top-8 bottom-8 z-30 w-[min(370px,calc(100%-4rem))] overflow-y-auto rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)]/98 shadow-2xl backdrop-blur-md"><div className="flex items-center justify-between border-b border-[var(--ms-border)] p-4"><div><p className="text-sm font-semibold">{hub.name}</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">{hub.id} · Live hub details</p></div><button onClick={onClose} className="rounded p-1.5 text-[var(--ms-muted)] hover:bg-[var(--ms-hover)]"><X className="h-4 w-4" /></button></div><div className="grid grid-cols-2 gap-2 p-4"><MetricCard value={String(hub.available)} label="Available" color="text-[var(--ms-accent-strong)]" /><MetricCard value={String(hub.capacity - hub.available)} label="Occupied" /><MetricCard value="6" label="Scooters" color="text-[#60a4e7]" /><MetricCard value="4" label="E-bikes" color="text-[#b486e8]" /></div><div className="mx-4 grid grid-cols-3 gap-2"><MetricCard value={String(hub.trips)} label="Trips" /><MetricCard value="692 km" label="Distance" small /><MetricCard value={`${hub.battery}%`} label="Avg battery" /></div><div className="mx-4 mt-3 rounded-lg border border-[var(--ms-border)] p-3"><div className="mb-2 flex justify-between text-[10px]"><span className="text-[var(--ms-muted)]">Capacity utilization</span><span>{hub.utilization}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[#dbe4dd]" style={{ width: `${hub.utilization}%` }} /></div><p className="mt-2 text-[10px] text-[var(--ms-muted)]">{hub.capacity - hub.available} occupied · {hub.available} available slots</p></div><div className="p-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold">Live vehicles</p><button className="text-[10px] text-[#55dc93]">View fleet</button></div><div className="space-y-2">{["E-Bike V3", "E-Bike V4", "Scooter V2"].map((name, index) => <div key={name} className="flex items-center justify-between rounded-lg border border-[var(--ms-border)] p-3"><div><p className="text-xs font-medium">{name}</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">{index === 0 ? "Moving · now" : "Stationed · 8m ago"}</p></div><span className={`text-xs font-semibold ${index === 1 ? "text-[#ef655a]" : "text-[var(--ms-accent-strong)]"}`}>{[76, 22, 64][index]}%</span></div>)}</div></div></aside> }
function Metric({ value, label, color = "text-[var(--ms-body)]" }: { value: string; label: string; color?: string }) { return <div className="text-center"><p className={`text-lg font-semibold tracking-[-0.04em] ${color}`}>{value}</p><p className="mt-1 text-[9px] text-[var(--ms-muted)]">{label}</p></div> }
function MetricCard({ value, label, color = "text-[var(--ms-body)]", small }: { value: string; label: string; color?: string; small?: boolean }) { return <div className="rounded-lg border border-[var(--ms-border)] p-3 text-center"><p className={`${small ? "text-[11px]" : "text-lg"} font-semibold ${color}`}>{value}</p><p className="mt-1 text-[9px] text-[var(--ms-muted)]">{label}</p></div> }
function Notice({ color, text }: { color: "amber" | "red" | "blue"; text: string }) { const colors = { amber: "bg-[#d99e22]/15 text-[#dfaf4f]", red: "bg-[#d9574f]/15 text-[#e57d74]", blue: "bg-[#458bd1]/15 text-[#75a9e2]" }; return <div className={`flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-left text-[10px] ${colors[color]}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{text}</div> }
