import { useState } from "react";
import { X } from "lucide-react";
import { Link } from "react-router-dom";
import MilestrideShell from "@/components/MilestrideShell";
import FleetMap from "@/components/FleetMap";
import { type Hub } from "@/lib/milestride";

export default function Overview() {
  const [selectedHub, setSelectedHub] = useState<Hub | null>(null);
  return <MilestrideShell><div className="relative h-full overflow-hidden p-3 sm:p-5"><FleetMap onHubClick={setSelectedHub} />{selectedHub && <HubDrawer hub={selectedHub} onClose={() => setSelectedHub(null)} />}</div></MilestrideShell>;
}

function HubDrawer({ hub, onClose }: { hub: Hub; onClose: () => void }) { return <aside className="absolute right-8 top-8 bottom-8 z-30 w-[min(370px,calc(100%-4rem))] overflow-y-auto rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)]/98 shadow-2xl backdrop-blur-md"><div className="flex items-center justify-between border-b border-[var(--ms-border)] p-4"><div><p className="text-sm font-semibold">{hub.name}</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">{hub.id} · Live hub details</p></div><button onClick={onClose} className="rounded p-1.5 text-[var(--ms-muted)] hover:bg-[var(--ms-hover)]"><X className="h-4 w-4" /></button></div><div className="grid grid-cols-2 gap-2 p-4"><MetricCard value={String(hub.available)} label="Available" color="text-[var(--ms-accent-strong)]" /><MetricCard value={String(hub.capacity - hub.available)} label="Occupied" /><MetricCard value="6" label="Scooters" color="text-[#60a4e7]" /><MetricCard value="4" label="E-bikes" color="text-[#b486e8]" /></div><div className="mx-4 grid grid-cols-3 gap-2"><MetricCard value={String(hub.trips)} label="Trips" /><MetricCard value="692 km" label="Distance" small /><MetricCard value={`${hub.battery}%`} label="Avg battery" /></div><div className="mx-4 mt-3 rounded-lg border border-[var(--ms-border)] p-3"><div className="mb-2 flex justify-between text-[10px]"><span className="text-[var(--ms-muted)]">Capacity utilization</span><span>{hub.utilization}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[#dbe4dd]" style={{ width: `${hub.utilization}%` }} /></div><p className="mt-2 text-[10px] text-[var(--ms-muted)]">{hub.capacity - hub.available} occupied · {hub.available} available slots</p></div><div className="p-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold">Live vehicles</p><Link to="/fleet" className="text-[10px] text-[var(--ms-accent)]">View fleet</Link></div><div className="space-y-2">{["E-Bike V3", "E-Bike V4", "Scooter V2"].map((name, index) => <div key={name} className="flex items-center justify-between rounded-lg border border-[var(--ms-border)] p-3"><div><p className="text-xs font-medium">{name}</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">{index === 0 ? "Moving · now" : "Stationed · 8m ago"}</p></div><span className={`text-xs font-semibold ${index === 1 ? "text-[#ef655a]" : "text-[var(--ms-accent-strong)]"}`}>{[76, 22, 64][index]}%</span></div>)}</div></div></aside> }
function MetricCard({ value, label, color = "text-[var(--ms-body)]", small }: { value: string; label: string; color?: string; small?: boolean }) { return <div className="rounded-lg border border-[var(--ms-border)] p-3 text-center"><p className={`${small ? "text-[11px]" : "text-lg"} font-semibold ${color}`}>{value}</p><p className="mt-1 text-[9px] text-[var(--ms-muted)]">{label}</p></div> }
