import { useMemo, useState } from "react";
import { BarChart3, Battery, CalendarDays, Check, ChevronDown, Download, FileText, Gauge, ShieldCheck, Wrench } from "lucide-react";
import { fleetOptions, allHubs, allVehicles } from "@/lib/milestride";
import { useMilestrideFleet } from "@/components/MilestrideShell";

const reportTypes = ["Fleet performance", "Hub performance", "Charging and battery", "Maintenance costs"];
const ranges = ["Today", "Last 7 days", "Last 30 days"];

export default function ReportsDashboard() {
  const { fleetId } = useMilestrideFleet();
  const [reportType, setReportType] = useState(reportTypes[0]);
  const [range, setRange] = useState(ranges[1]);
  const fleet = fleetOptions.find((item) => item.id === fleetId) ?? fleetOptions[0];
  const hubs = allHubs.filter((hub) => fleet.hubNames.includes(hub.name));
  const vehicles = allVehicles.filter((vehicle) => fleet.hubNames.includes(vehicle.hub));
  const metrics = useMemo(() => ({
    utilization: fleetId === "bellandur" ? "74%" : "68%",
    rides: fleetId === "bellandur" ? "2,146" : "1,284",
    compliance: fleetId === "bellandur" ? "98%" : "97%",
    maintenance: fleetId === "bellandur" ? "$4,820" : "$3,640",
  }), [fleetId]);
  const trend = fleetId === "bellandur" ? [52, 61, 57, 69, 72, 76, 73, 82, 86, 84, 91] : [48, 56, 52, 64, 61, 73, 68, 79, 76, 84, 81];

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)] p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[var(--ms-accent-soft)] text-[var(--ms-accent)]"><FileText className="h-4 w-4" /></span><div><p className="text-sm font-semibold">{reportType}</p><p className="mt-1 text-[11px] text-[var(--ms-muted)]">{fleet.name} fleet · {range} · Generated just now</p></div></div><div className="flex flex-wrap items-center gap-2"><ReportSelect label="Report" value={reportType} onChange={setReportType} options={reportTypes} /><ReportSelect label="Range" value={range} onChange={setRange} options={ranges} /><button className="ms-primary-button"><Download className="h-3.5 w-3.5" /> Export report</button></div></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><ReportMetric icon={<Gauge className="h-4 w-4" />} label="Fleet utilization" value={metrics.utilization} tone="text-[var(--ms-accent-strong)]" /><ReportMetric icon={<BarChart3 className="h-4 w-4" />} label="Completed rides" value={metrics.rides} tone="text-[#69a7de]" /><ReportMetric icon={<ShieldCheck className="h-4 w-4" />} label="Zone compliance" value={metrics.compliance} tone="text-[#e6b542]" /><ReportMetric icon={<Wrench className="h-4 w-4" />} label="Maintenance cost" value={metrics.maintenance} tone="text-[#b486e8]" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)] p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold">Fleet utilization report</h2><p className="mt-1 text-[11px] text-[var(--ms-muted)]">Hourly utilization across {fleet.name} operating hubs.</p></div><span className="text-[10px] font-semibold text-[var(--ms-accent-strong)]">Target 70%</span></div><div className="mt-6 flex h-52 items-end gap-2 border-b border-[var(--ms-border)] px-1">{trend.map((value, index) => <div key={index} className="group flex h-full flex-1 flex-col justify-end gap-2"><div className="relative rounded-t bg-[var(--ms-accent-strong)]/80 transition group-hover:bg-[var(--ms-accent-strong)]" style={{ height: `${value}%` }}><span className="absolute -top-5 left-1/2 hidden -translate-x-1/2 text-[9px] text-[var(--ms-muted)] group-hover:block">{value}%</span></div><span className="text-center text-[9px] text-[var(--ms-muted)]">{index + 9}:00</span></div>)}</div><div className="mt-4 flex flex-wrap gap-4 text-[10px] text-[var(--ms-muted)]"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-sm bg-[var(--ms-accent-strong)]" /> Utilization</span><span>Peak demand: 5–7 PM</span><span>{hubs.length} hubs included</span></div></section><section className="rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)] p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold">Report controls</h2><p className="mt-1 text-[11px] text-[var(--ms-muted)]">Change the report view.</p></div><CalendarDays className="h-4 w-4 text-[var(--ms-accent)]" /></div><div className="mt-5 space-y-4"><ReportSelect label="Report type" value={reportType} onChange={setReportType} options={reportTypes} /><ReportSelect label="Date range" value={range} onChange={setRange} options={ranges} /><div className="rounded-lg border border-[var(--ms-border)] bg-[var(--ms-bg)]/50 p-3"><p className="text-[10px] text-[var(--ms-muted)]">Included assets</p><p className="mt-1 text-sm font-semibold">{vehicles.length} vehicles · {hubs.length} hubs</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">Filtered to the active global fleet</p></div></div></section></div>
    <section className="rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)] p-5"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-sm font-semibold">Hub performance detail</h2><p className="mt-1 text-[11px] text-[var(--ms-muted)]">Availability, utilization, and trips by hub.</p></div><button className="ms-control">Download CSV</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] border-collapse text-left text-xs"><thead><tr className="border-b border-[var(--ms-border)] text-[10px] uppercase tracking-[0.1em] text-[var(--ms-muted)]"><th className="px-3 pb-3">Hub</th><th className="px-3 pb-3">Vehicles</th><th className="px-3 pb-3">Utilization</th><th className="px-3 pb-3">Availability</th><th className="px-3 pb-3">Trips</th><th className="px-3 pb-3">Status</th></tr></thead><tbody>{hubs.map((hub) => <tr key={hub.id} className="border-b border-[var(--ms-border)] last:border-0"><td className="px-3 py-3 font-medium">{hub.name}</td><td className="px-3 py-3">{hub.available}</td><td className="px-3 py-3">{hub.utilization}%</td><td className="px-3 py-3 font-semibold">{Math.max(70, 100 - hub.utilization / 2)}%</td><td className="px-3 py-3">{hub.trips}</td><td className="px-3 py-3"><span className={`ms-status ${hub.state === "critical" ? "status-red" : hub.state === "warning" ? "status-amber" : "status-green"}`}>{hub.state === "critical" ? "At risk" : hub.state}</span></td></tr>)}</tbody></table></div></section>
    <section className="grid gap-5 md:grid-cols-3"><Insight title="Battery health" icon={<Battery className="h-4 w-4" />} value={`${Math.round(vehicles.reduce((sum, vehicle) => sum + vehicle.battery, 0) / Math.max(vehicles.length, 1))}%`} detail="Average fleet battery" /><Insight title="Maintenance" icon={<Wrench className="h-4 w-4" />} value={`${vehicles.filter((vehicle) => vehicle.status === "Maintenance").length + 2}`} detail="Open work orders" /><Insight title="Compliance" icon={<ShieldCheck className="h-4 w-4" />} value={metrics.compliance} detail="Vehicles inside zones" /></section>
  </div>;
}

function ReportMetric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: string }) { return <div className="min-h-[108px] rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)] p-4"><span className={tone}>{icon}</span><p className={`mt-4 text-2xl font-semibold ${tone}`}>{value}</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">{label}</p></div>; }
function ReportSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) {
  const [open, setOpen] = useState(false);
  return <div className="relative"><span className="sr-only">{label}</span><button type="button" aria-label={`Select ${label.toLowerCase()}`} aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((current) => !current)} className="flex h-9 min-w-[126px] items-center justify-between gap-2 rounded-md border border-[var(--ms-border)] bg-[var(--ms-bg)] px-2.5 text-[10px] font-semibold text-[var(--ms-body)] transition hover:border-[var(--ms-accent-strong)] hover:bg-[var(--ms-hover)]"><span>{value}</span><ChevronDown aria-hidden="true" className={`h-3 w-3 text-[var(--ms-muted)] transition-transform ${open ? "rotate-180" : ""}`} /></button>{open && <div role="listbox" aria-label={label} className="ms-popover right-0 top-11 min-w-full"><p className="px-2.5 py-1.5 text-[9px] font-semibold uppercase tracking-[0.14em] text-[var(--ms-muted)]">{label}</p>{options.map((option) => <button key={option} type="button" role="option" aria-selected={option === value} onClick={() => { onChange(option); setOpen(false); }} className={`flex w-full items-center justify-between rounded-md px-2.5 py-2 text-left text-[10px] transition ${option === value ? "bg-[var(--ms-accent-soft)] text-[var(--ms-accent)]" : "text-[var(--ms-body)] hover:bg-[var(--ms-hover)]"}`}><span>{option}</span>{option === value && <Check aria-hidden="true" className="h-3 w-3" />}</button>)}</div>}</div>;
}
function Insight({ title, icon, value, detail }: { title: string; icon: React.ReactNode; value: string; detail: string }) { return <div className="rounded-xl border border-[var(--ms-border)] bg-[var(--ms-panel)] p-4"><div className="flex items-center gap-2 text-[var(--ms-accent)]">{icon}<p className="text-xs font-semibold">{title}</p></div><p className="mt-5 text-2xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">{detail}</p></div>; }
