import { useEffect, useState, type CSSProperties, type ReactNode } from "react";
import { ChevronDown, MapPin, Navigation } from "lucide-react";
import { hubs, vehicles, type Hub, type Vehicle } from "@/lib/milestride";
import { useMilestrideTheme } from "@/components/MilestrideShell";

const hubColors = { healthy: "#45dd89", warning: "#e8b846", critical: "#ef655a" };

export default function FleetMap({ onHubClick, docked = false }: { onHubClick?: (hub: Hub) => void; docked?: boolean }) {
  const { theme } = useMilestrideTheme();
  const [trackedVehicleId, setTrackedVehicleId] = useState<string | null>(null);
  const [trackMenuOpen, setTrackMenuOpen] = useState(false);
  const [liveVehicles, setLiveVehicles] = useState(vehicles);
  const trackedVehicle = liveVehicles.find((vehicle) => vehicle.id === trackedVehicleId);

  useEffect(() => {
    const timer = window.setInterval(() => setLiveVehicles((current) => current.map((vehicle) => vehicle.status === "Moving" ? { ...vehicle, x: vehicle.x + (Math.random() - .5) * .7, y: vehicle.y + (Math.random() - .5) * .7 } : vehicle)), 3500);
    return () => window.clearInterval(timer);
  }, []);

  return <section className={`ms-map ${docked ? "rounded-xl border border-[var(--ms-border)]" : ""}`}>
    <div className="absolute inset-0 map-grid opacity-80" /><div className="absolute inset-0 map-roads opacity-60" />
    <div className="relative z-10 flex items-center justify-between border-b border-[var(--ms-border)] bg-[var(--ms-surface)]/80 px-4 py-3 backdrop-blur-sm sm:px-6"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--ms-muted)]">Live network map</p><p className="mt-1 text-sm font-semibold">Electronics City · Bengaluru</p></div><div className="hidden items-center gap-2 text-[11px] text-[var(--ms-muted)] sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[var(--ms-accent-strong)] shadow-[0_0_10px_var(--ms-accent-strong)]" /> Live hub data · just now</div></div>
    <div className="relative z-10 flex items-center gap-2 px-4 pt-4 sm:px-6"><span className="rounded-md border border-[var(--ms-accent-strong)]/35 bg-[var(--ms-accent-soft)] px-2.5 py-1.5 text-[11px] font-medium text-[var(--ms-accent)]">Hubs</span><span className="text-[11px] text-[var(--ms-muted)]">Select a vehicle below to track its live position</span></div>
    {hubs.map((hub) => <button key={hub.id} onClick={() => onHubClick?.(hub)} className="group absolute z-10 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center" style={{ left: `${hub.x}%`, top: `calc(${hub.y}% + 64px)` }}><span className="relative flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#1a1d1c]" style={{ backgroundColor: hubColors[hub.state], boxShadow: `0 0 18px ${hubColors[hub.state]}80` }}><MapPin className="h-4 w-4 fill-current text-[#18201b]" /><span className="absolute inset-[-5px] rounded-full border border-current opacity-20 group-hover:animate-ping" style={{ color: hubColors[hub.state] }} /></span><span className={`mt-1.5 whitespace-nowrap rounded px-2 py-1 text-[10px] shadow-lg ${theme === "dark" ? "bg-[#131615]/90 text-[#dae2dc]" : "bg-white/90 text-[#24332a]"}`}>{hub.name}<span className="ml-1.5 opacity-60">{hub.available} available</span></span></button>)}
    {trackedVehicle && <VehicleMarker vehicle={trackedVehicle} moving={trackedVehicle.status === "Moving"} />}
    <div className={`absolute bottom-5 left-5 z-20 w-[min(320px,calc(100%-2.5rem))] rounded-xl border border-[var(--ms-border)] p-4 shadow-2xl backdrop-blur-md ${theme === "dark" ? "bg-[#171b19]/95" : "bg-white/95"}`}><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-semibold">Fleet activity</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">{trackedVehicle ? `Tracking ${trackedVehicle.id}` : "Hubs only · no vehicle selected"}</p></div><span className="flex items-center gap-1.5 text-[10px] text-[var(--ms-accent-strong)]"><span className="h-1.5 w-1.5 rounded-full bg-current" /> Live</span></div><div className="grid grid-cols-3 divide-x divide-[var(--ms-border)]"><MapMetric value="2" label="Moving" color="text-[var(--ms-accent-strong)]" /><MapMetric value="2" label="Stationed" /><MapMetric value="4" label="Hubs" color="text-[#68a6df]" /></div><div className="relative mt-3"><button onClick={() => setTrackMenuOpen((open) => !open)} className="flex h-9 w-full items-center justify-between rounded-md border border-[var(--ms-border)] bg-[var(--ms-bg)] px-3 text-[11px] font-medium text-[var(--ms-body)] hover:bg-[var(--ms-hover)]"><span>{trackedVehicle ? "Change tracked vehicle" : "Track a vehicle"}</span><ChevronDown className={`h-3.5 w-3.5 transition-transform ${trackMenuOpen ? "rotate-180" : ""}`} /></button>{trackMenuOpen && <div className="absolute bottom-11 left-0 right-0 z-30 max-h-48 overflow-y-auto rounded-md border border-[var(--ms-border)] bg-[var(--ms-panel)] p-1 shadow-xl">{liveVehicles.map((vehicle) => <button key={vehicle.id} onClick={() => { setTrackedVehicleId(vehicle.id); setTrackMenuOpen(false); }} className="flex w-full items-center justify-between rounded px-2.5 py-2 text-left text-[10px] hover:bg-[var(--ms-hover)]"><span>{vehicle.id}</span><span className={vehicle.status === "Moving" ? "text-[#69a7de]" : "text-[var(--ms-muted)]"}>{vehicle.status}</span></button>)}</div>}</div>{trackedVehicle && <button onClick={() => setTrackedVehicleId(null)} className="mt-2 w-full text-[10px] text-[var(--ms-muted)] underline-offset-2 hover:text-[var(--ms-body)] hover:underline">Stop tracking · return to hubs only</button>}</div>
  </section>;
}
function VehicleMarker({ vehicle, moving }: { vehicle: Vehicle; moving: boolean }) { const style: CSSProperties = { left: `${vehicle.x}%`, top: `calc(${vehicle.y}% + 64px)` }; return <div className="absolute z-10 -translate-x-1/2 -translate-y-1/2" style={style}><div className={`relative flex h-7 w-7 items-center justify-center rounded-full border-2 border-[#17201a] ${moving ? "bg-[#6fabe1] shadow-[0_0_14px_#6fabe1]" : "bg-[#8d9a91]"}`} title={`${vehicle.id} · ${moving ? "Moving" : `Stationed at ${vehicle.hub}`}`}><span className="text-[#17201a]">{moving ? <Navigation className="h-3.5 w-3.5 fill-current" /> : <span className="h-2 w-2 rounded-full bg-current" />}</span>{moving && <span className="absolute inset-[-4px] animate-ping rounded-full border border-[#6fabe1]/40" />}</div><div className="mt-1 whitespace-nowrap rounded bg-[#121614]/80 px-1.5 py-0.5 text-[9px] text-white/80">{vehicle.id} · {vehicle.battery}%</div></div> }
function MapMetric({ value, label, color = "text-[var(--ms-body)]" }: { value: string; label: string; color?: string }) { return <div className="text-center"><p className={`text-lg font-semibold ${color}`}>{value}</p><p className="mt-1 text-[9px] text-[var(--ms-muted)]">{label}</p></div> }
