import { useEffect, useState, type CSSProperties } from "react";
import { Activity, ChevronDown, LocateFixed, MapPin, Minus, Navigation, Plus, Search, Truck } from "lucide-react";
import { hubs, vehicles, type Hub } from "@/lib/milestride";
import { useMilestrideTheme } from "@/components/MilestrideShell";

const hubColors = { healthy: "#45dd89", warning: "#e8b846", critical: "#ef655a" };

export default function FleetMap({ onHubClick, docked = false }: { onHubClick?: (hub: Hub) => void; docked?: boolean }) {
  const { theme } = useMilestrideTheme();
  const [moving, setMoving] = useState(vehicles.filter((vehicle) => vehicle.status === "Moving"));
  useEffect(() => { const timer = window.setInterval(() => setMoving((current) => current.map((vehicle) => ({ ...vehicle, x: vehicle.x + (Math.random() - .5) * .7, y: vehicle.y + (Math.random() - .5) * .7 }))), 3500); return () => window.clearInterval(timer); }, []);
  return <section className={`ms-map ${docked ? "rounded-xl border border-[var(--ms-border)]" : ""}`}>
    <div className="absolute inset-0 map-grid opacity-80" /><div className="absolute inset-0 map-roads opacity-60" />
    <div className="relative z-10 flex items-center justify-between border-b border-[var(--ms-border)] bg-[var(--ms-surface)]/80 px-4 py-3 backdrop-blur-sm sm:px-6"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--ms-muted)]">Live network map</p><p className="mt-1 text-sm font-semibold">Electronics City · Bengaluru</p></div><div className="hidden items-center gap-2 text-[11px] text-[var(--ms-muted)] sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#4bdc8b] shadow-[0_0_10px_#4bdc8b]" /> Live vehicle data · just now</div></div>
    <div className="relative z-10 flex flex-wrap gap-2 px-4 pt-4 sm:px-6"><MapTool label="Filters" icon={<Activity className="h-3 w-3" />} /><MapTool label="Vehicles" icon={<Truck className="h-3 w-3" />} active /><MapTool label="Hubs" icon={<MapPin className="h-3 w-3" />} /></div>
    <div className="absolute right-5 top-24 z-10 flex flex-col overflow-hidden rounded-md border border-[var(--ms-border)] bg-[var(--ms-surface)]/90 shadow-lg backdrop-blur-sm"><button className="p-2.5 text-[var(--ms-muted)] hover:bg-[var(--ms-hover)]"><Search className="h-4 w-4" /></button><div className="h-px bg-[var(--ms-border)]" /><button className="p-2.5 text-[var(--ms-muted)] hover:bg-[var(--ms-hover)]"><Plus className="h-4 w-4" /></button><div className="h-px bg-[var(--ms-border)]" /><button className="p-2.5 text-[var(--ms-muted)] hover:bg-[var(--ms-hover)]"><Minus className="h-4 w-4" /></button><div className="h-px bg-[var(--ms-border)]" /><button className="p-2.5 text-[var(--ms-muted)] hover:bg-[var(--ms-hover)]"><LocateFixed className="h-4 w-4" /></button></div>
    {hubs.map((hub) => <button key={hub.id} onClick={() => onHubClick?.(hub)} className="group absolute z-10 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center" style={{ left: `${hub.x}%`, top: `calc(${hub.y}% + 64px)` }}><span className="relative flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#1a1d1c]" style={{ backgroundColor: hubColors[hub.state], boxShadow: `0 0 18px ${hubColors[hub.state]}80` }}><MapPin className="h-4 w-4 fill-current text-[#18201b]" /><span className="absolute inset-[-5px] rounded-full border border-current opacity-20 group-hover:animate-ping" style={{ color: hubColors[hub.state] }} /></span><span className={`mt-1.5 whitespace-nowrap rounded px-2 py-1 text-[10px] shadow-lg ${theme === "dark" ? "bg-[#131615]/90 text-[#dae2dc]" : "bg-white/90 text-[#24332a]"}`}>{hub.name}<span className="ml-1.5 opacity-60">{hub.available} available</span></span></button>)}
    {moving.map((vehicle) => <VehicleMarker key={vehicle.id} vehicle={vehicle} moving />)}
    {vehicles.filter((vehicle) => vehicle.status === "Stationed").map((vehicle) => <VehicleMarker key={vehicle.id} vehicle={vehicle} moving={false} />)}
    <div className={`absolute bottom-5 left-5 z-10 w-[275px] rounded-xl border border-[var(--ms-border)] p-4 shadow-2xl backdrop-blur-md ${theme === "dark" ? "bg-[#171b19]/95" : "bg-white/95"}`}><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-semibold">Fleet activity</p><p className="mt-1 text-[10px] text-[var(--ms-muted)]">Current vehicle positions</p></div><span className="flex items-center gap-1.5 text-[10px] text-[#49dc89]"><span className="h-1.5 w-1.5 rounded-full bg-current" /> Live</span></div><div className="grid grid-cols-3 divide-x divide-[var(--ms-border)]"><MapMetric value="2" label="Moving" color="text-[#4cde8c]" /><MapMetric value="2" label="Stationed" /><MapMetric value="4" label="Hubs" color="text-[#68a6df]" /></div><div className="mt-3 flex items-center gap-2 text-[10px] text-[var(--ms-muted)]"><Navigation className="h-3 w-3 text-[#4cde8c]" /> Moving vehicles refresh every few seconds</div></div>
  </section>;
}
function MapTool({ label, icon, active }: { label: string; icon: React.ReactNode; active?: boolean }) { return <button className={`flex items-center gap-1.5 rounded-md border px-2.5 py-1.5 text-[11px] transition ${active ? "border-[#4bdc8b]/40 bg-[#3edb85]/10 text-[#55dc93]" : "border-[var(--ms-border)] bg-[var(--ms-surface)]/80 text-[var(--ms-muted)] hover:bg-[var(--ms-hover)]"}`}>{icon}{label}</button> }
function VehicleMarker({ vehicle, moving }: { vehicle: typeof vehicles[number]; moving: boolean }) { const style: CSSProperties = { left: `${vehicle.x}%`, top: `calc(${vehicle.y}% + 64px)` }; return <div className="absolute z-10 -translate-x-1/2 -translate-y-1/2" style={style}><div className={`relative flex h-6 w-6 items-center justify-center rounded-full border-2 border-[#17201a] ${moving ? "bg-[#6fabe1] shadow-[0_0_14px_#6fabe1]" : "bg-[#8d9a91]"}`} title={`${vehicle.id} · ${moving ? "Moving" : `Stationed at ${vehicle.hub}`}`}><span className="text-[#17201a]">{moving ? <Navigation className="h-3 w-3 fill-current" /> : <span className="h-2 w-2 rounded-full bg-current" />}</span>{moving && <span className="absolute inset-[-4px] animate-ping rounded-full border border-[#6fabe1]/40" />}</div><div className="mt-1 whitespace-nowrap rounded bg-[#121614]/80 px-1.5 py-0.5 text-[9px] text-white/80">{vehicle.id}</div></div> }
function MapMetric({ value, label, color = "text-[var(--ms-body)]" }: { value: string; label: string; color?: string }) { return <div className="text-center"><p className={`text-lg font-semibold ${color}`}>{value}</p><p className="mt-1 text-[9px] text-[var(--ms-muted)]">{label}</p></div> }
